### ISSUE TITLE
Add support to enable plugin in runtime 

### ISSUE THREAD

**Issue by 66Ton99** [Zitrax/nose-dep#6]
Some times tests fails without depended (ordered) tests but it must pass even without `--with-nosedep` option.

**Comment by Zitrax** [comment]
I don't understand exactly what you mean, can you give an example ?

**Comment by 66Ton99** [comment]
Now it works only in case you add option `nosetests --with-nosedep SomeTest.py` but it should work without it.

**Comment by Zitrax** [comment]
But that sounds like it's due to the tests. Or do you mean that you would like `--with-nosedep` to be the default ?

**Comment by Zitrax** [comment]
Closing due to lack of information. You can reopen if you have further feedback.
